Repository WildCodeSchool/2109-wns-remote2-excelant, pull requests merged in 2022-01, with the labels that each got.

#23 implement container on pages
  web-client/src/pages/HomePage.tsx
  web-client/src/pages/ProjectsPage.tsx
  web-client/src/pages/TasksPage.tsx
  web-client/src/pages/UsersPage.tsx
Labels: ready for merge

#26 Feature/task component
  web-client/.eslintrc.json
  web-client/package-lock.json
  web-client/package.json
  web-client/src/components/tasks/CreateTaskModal.tsx
  web-client/src/components/tasks/TaskTable.tsx
  web-client/src/pages/TasksPage.tsx
Labels: ready for merge

#34 fix unwanted display
  .gitignore
  web-client/src/components/tasks/CreateTaskModal.tsx
  web-client/src/components/tasks/TaskTable.tsx
Labels: review needed, client

#28 Docker
  .gitignore
  Makefile
  README.md
  docker-compose.dev.yml
  docker-compose.yml
  server/.dockerignore
  server/Dockerfile
  server/config/default.ts
  web-client/.dockerignore
  web-client/Dockerfile
Labels: review needed, devOps

#33 Feature/show add project
  web-client/package-lock.json
  web-client/src/components/projects/CreateProjectModal.tsx
  web-client/src/components/projects/ProjectsTable.tsx
  web-client/src/pages/ProjectsPage.tsx
Labels: enhancement, review needed

#44 40 change task creation design
  web-client/src/_utils/modalStyle.ts
  web-client/src/components/tasks/CreateTaskModal.tsx
Labels: review needed, client

#43 done for project entity
  server/src/resolvers/index.ts
  server/src/resolvers/project.resolver.ts
  server/src/schema/project.create.ts
  server/src/schema/project.schema.ts
  server/src/service/project.service.ts
Labels: review needed, server

#50 Node version
  README.md
  server/.nvmrc
  web-client/.nvmrc
Labels: review needed

#54 clean imports and apply design on project creation modal
  web-client/src/components/projects/CreateProjectModal.tsx
  web-client/src/components/tasks/CreateTaskModal.tsx
Labels: ready for merge, client

#57 chore(package): rebuild package-locks with node 14.17
  package-lock.json
  server/package-lock.json
  web-client/package-lock.json
Labels: ready for merge

#59 fix(Link.test.tsx) added Appolo's MockedProvider
  web-client/src/pages/HomePage.tsx
  web-client/src/pages/ProjectsPage.tsx
  web-client/src/tests/Link.test.tsx
Labels: review needed

#61 fix test ci folder
  .github/workflows/test-ci.yml
Labels: review needed

#60 feature: project status
  web-client/src/components/projects/CreateProjectModal.tsx
Labels: review needed, client

#62 Modal ticket details
  web-client/src/_utils/modalStyle.ts
  web-client/src/components/modal/TaskModal.scss
  web-client/src/components/modal/TaskModal.tsx
  web-client/src/components/tasks/TaskTable.tsx
  web-client/src/variables/_variables.scss
Labels: review needed
